### ISSUE TITLE
8.8.3 references dbr-8.8.0.node.wasm file

### ISSUE THREAD

**Issue by jkrnl** [Dynamsoft/javascript-barcode#105]
Hi There,

v8.8.0 works like charm here, but I'm struggling to use **8.8.3** in node.js. Runtime this error appears:
RuntimeError: abort(Error: ENOENT: no such file or directory, open 'c:\Users\xy\source\repos\testool\node_modules\dynamsoft-javascript-barcode\dist\dbr-**8.8.0.node.wasm'**) at Error
dist folder contains 8.8.3 files correctly.

I found that [dbr-8.8.3.node.wasm.js](https://github.com/Dynamsoft/javascript-barcode/blob/main/dist/dbr-8.8.3.node.wasm.js) contains reference to **8.8.0.node.wasm**: 
"var H;H="dbr-8.8.0.node.wasm";if(!kb())"
Is it intentional?

Please, could you check and help to find out the solution?
(npm install/uninstall, node_modules folder cleanup etc. has already been performed)
Thank you

**Comment by Keillion** [comment]
`keillion-dynamsoft-javascript-barcode@0.20220110081920.0`

A quick fixed version.

Will be officailly fixed in 8.8.5.

**Comment by jkrnl** [comment]
Thanks, my trial licence does not seem to work with this version :)
So let me wait for v8.8.5 then. Do you have any ETA?
Thank you

**Comment by Cube-J** [comment]
v8.8.7 has been released and the bug is fixed.

**Comment by jkrnl** [comment]
Sounds great, thanks a lot!

**Comment by Keillion** [comment]
dynamsoft-node-barcode@8.8.7 fixed
https://www.npmjs.com/package/dynamsoft-node-barcode
