### ISSUE TITLE
Unable to get camera capability. TypeError: null is not an object (evaluating 'this._videoTrack.getCapabilities')

### ISSUE THREAD

**Issue by mehran-01** [Dynamsoft/javascript-barcode#66]
Trying the demo on IOS via Chrome browser v 83

Getting error:
Unable to get camera capability. TypeError: null is not an object (evaluating 'this._videoTrack.getCapabilities')

Works on same device but Safari

**Comment by yushulx** [comment]
@mehran-01 Apple only makes Safari support WebRTC. If you want to make the camera work in iOS Chrome, please be patient to wait for iOS updates.
