### ISSUE TITLE
getting barcode image marked with detection results

### ISSUE THREAD

**Issue by bmabir17** [Dynamsoft/javascript-barcode#73]
I am trying to get results from image files using the [Dynamsoft.DBR.BarcodeReader](https://www.dynamsoft.com/barcode-reader/programming/javascript/api-reference/BarcodeReader/methods/decode.html?ver=latest#decode) as follows

```js
reader = reader || await Dynamsoft.DBR.BarcodeReader.createInstance();
let results = await reader.decode(this.files[0]);
let res_img = await reader.getIntermediateResults();

```
I am getting the results of the bar code as text. But i also want the image that is marked with the bar code location. would i be able to get that using `getIntermediateResults();
` method ?

**Comment by Keillion** [comment]
@bmabir17 
[oriCanvas](https://dynamsoft.github.io/javascript-barcode/doc/api%20reference/classes/barcodescanner.html#oricanvas) saves the source image in a canvas.
While you need draw the barcode location yourself using [localizationresult](https://dynamsoft.github.io/javascript-barcode/doc/api%20reference/interfaces/textresult.html#localizationresult).

some sample code copy from BarcodeScanner:
```js
ctx.fillStyle = this.barcodeFillStyle;
ctx.strokeStyle = this.barcodeStrokeStyle;
ctx.lineWidth = this.barcodeLineWidth;
results = results || [];
for(let result of results){
let loc = result.localizationResult;
  ctx.beginPath();
  ctx.moveTo(loc.x1, loc.y1);
  ctx.lineTo(loc.x2, loc.y2);
  ctx.lineTo(loc.x3, loc.y3);
  ctx.lineTo(loc.x4, loc.y4);
  ctx.fill();
  ctx.beginPath();
  ctx.moveTo(loc.x1, loc.y1);
  ctx.lineTo(loc.x2, loc.y2);
  ctx.lineTo(loc.x3, loc.y3);
  ctx.lineTo(loc.x4, loc.y4);
  ctx.closePath();
  ctx.stroke();
}
```
