### ISSUE TITLE
[8.1] Barcode result text in trial version has appended exception string

### ISSUE THREAD

**Issue by rubenkuipers** [Dynamsoft/javascript-barcode#76]
Hi there,

I'm using the barcode scanner 8.1 version that was released yesterday. 
Since we're still on the trial version (already have a contract for commercial version) an exception is added when a a barcode scan is succesful:

```barcodeText: "[Attention(exceptionCode:-20010)] 9783161484100"```

The last part is the barcode I need, the first part is some exception. Could this just be the clean output like it was in the previous version (8.0)? 

I already see a different exception object that is stating that I'm on the trial version, so I don't know why this is needed.

**Comment by Keillion** [comment]
@rubenkuipers A few users have reported this problem. After some discussion, we decide to remove `[Attention` in trial version. Thanks for your feedback. Dbrjs 8.1.2 will release today.

**Comment by rubenkuipers** [comment]
@Keillion thank you very much
